# Generated by Django 3.0.5 on 2021-05-28 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('promotion', '0001_initial'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(default='', max_length=70)),
                ('in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charged_courses', to='professor.Professor')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.Promotion')),
                ('registered_students', models.ManyToManyField(to='student.Student')),
            ],
        ),
    ]
