# Generated by Django 3.0.5 on 2021-05-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
