# Generated by Django 3.0.5 on 2021-05-28 01:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('firstName', models.CharField(default='', max_length=70)),
                ('lastName', models.CharField(default='', max_length=70)),
                ('phoneNumber', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('registration_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_year', models.PositiveIntegerField(default=0)),
                ('year_in_school', models.CharField(choices=[('FOND', 'Licence Fondamentale'), ('APP', 'Licence Appliquée'), ('MAR', 'Master de Recherche'), ('MAP', 'Master Professionel')], default='FOND', max_length=5)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='promotion.Promotion')),
            ],
        ),
    ]
